bind 0.0.0.0
port 6379
protected-mode no

appendonly yes
appendfsync everysec
dir /data

maxmemory 256mb
maxmemory-policy allkeys-lru

databases 16
timeout 0
tcp-keepalive 300

loglevel notice
slowlog-log-slower-than 10000
slowlog-max-len 128
