# --- CONNECTIONS ---
listen_addresses = '*'
max_connections = 100

# --- MEMORY CONFIG ---
shared_buffers = 256MB
work_mem = 4MB
maintenance_work_mem = 64MB
effective_cache_size = 768MB

# --- WRITE AHEAD LOG (WAL) ---
wal_buffers = 8MB
checkpoint_completion_target = 0.9
checkpoint_timeout = 15min
max_wal_size = 1GB
min_wal_size = 80MB

# --- SLOW QUERY LOGGING ---
log_min_duration_statement = 200
log_line_prefix = '%m [%p] %q%u@%d '
log_timezone = 'Asia/Ho_Chi_Minh'

# --- AUTOVACUUM ---
autovacuum = on
autovacuum_max_workers = 3
